name: Run Prettier
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Prettier
        run: npm install -g prettier@~3.0.3 && npx prettier --check .
